# Generated by Django 2.1 on 2018-08-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of your course (e.g. Intro to Woodworking)', max_length=200)),
                ('version', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(help_text='Enter a your course description', max_length=1000)),
                ('objectives', models.TextField(max_length=1000, null=True)),
                ('resources', models.TextField(max_length=1000, null=True)),
                ('grading_policy', models.TextField(max_length=1000, null=True)),
                ('assessment_practices', models.TextField(max_length=1000, null=True)),
                ('projects', models.TextField(max_length=1000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployabilityObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('classification', models.CharField(blank=True, choices=[('t', 'Topic'), ('s', 'Standard'), ('o', 'Objectcive')], default='t', help_text='Classify this competancy', max_length=1)),
            ],
            options={
                'ordering': ['strand'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_objectives', models.CharField(max_length=200, null=True)),
                ('language_objectives', models.CharField(max_length=200, null=True)),
                ('lesson_outline', models.TextField(max_length=1000, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Course')),
                ('employability_objectives', models.ManyToManyField(to='app.EmployabilityObjective')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('classification', models.CharField(blank=True, choices=[('t', 'Topic'), ('s', 'Standard'), ('o', 'Objectcive')], default='t', help_text='Classify this competancy', max_length=1)),
            ],
            options={
                'ordering': ['strand'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your program (e.g. Carpentry)', max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('classification', models.CharField(blank=True, choices=[('t', 'Topic'), ('s', 'Standard'), ('o', 'Objectcive')], default='t', help_text='Classify this competancy', max_length=1)),
            ],
            options={
                'ordering': ['strand'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('classification', models.CharField(blank=True, choices=[('t', 'Topic'), ('s', 'Standard'), ('o', 'Objectcive')], default='t', help_text='Classify this competancy', max_length=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program')),
            ],
            options={
                'ordering': ['strand'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('classification', models.CharField(blank=True, choices=[('t', 'Topic'), ('s', 'Standard'), ('o', 'Objectcive')], default='t', help_text='Classify this competancy', max_length=1)),
            ],
            options={
                'ordering': ['strand'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Program'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='management_objectives',
            field=models.ManyToManyField(to='app.ManagementObjective'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='resource_links',
            field=models.ManyToManyField(to='app.ResourceLink'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='safety_objectives',
            field=models.ManyToManyField(to='app.SafetyObjective'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='technical_objectives',
            field=models.ManyToManyField(to='app.TechnicalObjective'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='technology_objectives',
            field=models.ManyToManyField(to='app.TechnologyObjective'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Program'),
        ),
    ]
