# Generated by Django 2.1 on 2018-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Enter a your course description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='employability_objectives',
            field=models.ManyToManyField(blank=True, to='app.EmployabilityObjective'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='management_objectives',
            field=models.ManyToManyField(blank=True, to='app.ManagementObjective'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='resource_links',
            field=models.ManyToManyField(blank=True, to='app.ResourceLink'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='safety_objectives',
            field=models.ManyToManyField(blank=True, to='app.SafetyObjective'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='technical_objectives',
            field=models.ManyToManyField(blank=True, to='app.TechnicalObjective'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='technology_objectives',
            field=models.ManyToManyField(blank=True, to='app.TechnologyObjective'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
