# Generated by Django 2.1 on 2018-08-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180820_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employabilityobjective',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='managementobjective',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='technicalobjective',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='technologyobjective',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Taxonomy'),
        ),
    ]
