# Generated by Django 2.1 on 2018-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180820_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
