# Generated by Django 2.1 on 2018-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180822_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, help_text='List any prerequisite courses required.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sequence',
            field=models.CharField(blank=True, help_text='When viewing a course, Lesson Plans will be sorted by this value', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
